/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.kitt.snowboy;

public class SnowboyDetect {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected SnowboyDetect(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                snowboyJNI.delete_SnowboyDetect(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public SnowboyDetect(String resource_filename, String model_str) {
        this(snowboyJNI.new_SnowboyDetect(resource_filename, model_str), true);
    }

    public int runDetection(short[] data, int array_length) {
        return snowboyJNI.SnowboyDetect_RunDetection__SWIG_5(swigCPtr, this, data, array_length);
    }

    public void setSensitivity(String sensitivity_str) {
        snowboyJNI.SnowboyDetect_SetSensitivity(swigCPtr, this, sensitivity_str);
    }

    public void applyFrontend(boolean apply_frontend) {
        snowboyJNI.SnowboyDetect_ApplyFrontend(swigCPtr, this, apply_frontend);
    }
}
